apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.meta.name }}
  namespace: {{ .Values.meta.namespace }}
spec:
  maxReplicas: {{ .Values.meta.maxReplicas }}
  minReplicas: {{ .Values.meta.replicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.meta.name }}
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.resources.targetAverageUtilization }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.resources.targetAverageUtilization }}
